CREATE TABLE IF NOT EXISTS PUBLISHER (
  ID   INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(255)                   NOT NULL,
  DESC VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS  SKILL (
  ID   INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME VARCHAR(255)                   NOT NULL,
  DESC VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS  SUPERHERO (
  ID               INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME             VARCHAR(255)                   NOT NULL,
  PSEUDONYM        VARCHAR(255),
  FIRST_APPEARANCE TIMESTAMP,
  PUBLISHER_ID     INT                            NOT NULL,
  FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER (ID)
);
CREATE TABLE IF NOT EXISTS  SUPERHERO_POWER (
  ID           INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SUPERHERO_ID INT                            NOT NULL,
  SKILL_ID     INT                            NOT NULL,
  FOREIGN KEY (SUPERHERO_ID) REFERENCES SUPERHERO (ID),
  FOREIGN KEY (SKILL_ID) REFERENCES SKILL (ID)
);
CREATE TABLE IF NOT EXISTS SUPERHERO_ALLIANCE (
  ID           INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SUPERHERO_ID INT                            NOT NULL,
  ALLY_ID      INT                            NOT NULL,
  FOREIGN KEY (SUPERHERO_ID) REFERENCES SUPERHERO (ID),
  FOREIGN KEY (ALLY_ID) REFERENCES SUPERHERO (ID)
);



INSERT INTO SKILL (NAME, DESC) VALUES ('Fly', 'Fly');
INSERT INTO SKILL (NAME, DESC) VALUES ('Heat vision', 'Heat vision');
INSERT INTO SKILL (NAME, DESC) VALUES ('Telepathy', 'Telepathy');
INSERT INTO SKILL (NAME, DESC) VALUES ('Firestorm', 'Firestorm');
INSERT INTO SKILL (NAME, DESC) VALUES ('Nuclear physics', 'nuclear physics');
INSERT INTO SKILL (NAME, DESC) VALUES ('Speed', 'Superhuman Speed');
INSERT INTO SKILL (NAME, DESC) VALUES ('Strength', 'Superhuman Strength');
INSERT INTO SKILL (NAME, DESC) VALUES ('Transformation', 'Transformation');
INSERT INTO SKILL (NAME, DESC) VALUES ('Object-based powers', 'Powers derived from objects (AKA artifacts) i.e armor.');
INSERT INTO SKILL (NAME, DESC) VALUES ('Healing factor', 'healing factor');
INSERT INTO SKILL (NAME, DESC) VALUES ('Agility', 'Agility');









INSERT INTO PUBLISHER (NAME, DESC) VALUES ('DC', 'DC Comics');
INSERT INTO PUBLISHER (NAME, DESC) VALUES ('Marvel', 'Marvel Comics');
INSERT INTO PUBLISHER (NAME, DESC) VALUES ('Valiant', 'Valiant Comics');
INSERT INTO PUBLISHER (NAME, DESC) VALUES ('Charlton', 'Charlton Comics');






INSERT INTO SUPERHERO (NAME, PSEUDONYM, FIRST_APPEARANCE, PUBLISHER_ID)VALUES ('Superman', 'Clark Kent', '1938-06-01', 1);
INSERT INTO SUPERHERO (NAME, PSEUDONYM, FIRST_APPEARANCE, PUBLISHER_ID)VALUES ('HULK', 'Dr. Robert Bruce Banner', '1962-01-01', 2);
INSERT INTO SUPERHERO (NAME, PSEUDONYM, FIRST_APPEARANCE, PUBLISHER_ID) VALUES ('Wolverine', 'Logan', '1974-10-01', 2);
INSERT INTO SUPERHERO (NAME, PSEUDONYM, FIRST_APPEARANCE, PUBLISHER_ID) VALUES ('Thor', 'Thor Odinson', '1962-08-01', 2);
INSERT INTO SUPERHERO (NAME, PSEUDONYM, FIRST_APPEARANCE, PUBLISHER_ID) VALUES ('Batman', ' Bruce Wayne', '1963-03-01', 1);

INSERT INTO SUPERHERO_ALLIANCE (SUPERHERO_ID, ALLY_ID) VALUES (1, 4);
INSERT INTO SUPERHERO_ALLIANCE (SUPERHERO_ID, ALLY_ID) VALUES (2, 3);
INSERT INTO SUPERHERO_ALLIANCE (SUPERHERO_ID, ALLY_ID) VALUES (3, 2);
INSERT INTO SUPERHERO_ALLIANCE (SUPERHERO_ID, ALLY_ID) VALUES (4, 1);
INSERT INTO SUPERHERO_ALLIANCE (SUPERHERO_ID, ALLY_ID) VALUES (4, 2);
INSERT INTO SUPERHERO_ALLIANCE (SUPERHERO_ID, ALLY_ID) VALUES (2, 4);


INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (1, 1);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (1, 2);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (1, 6);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (1, 7);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (2, 8);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (2, 6);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (3, 10);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (3, 11);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (4, 1);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (4, 6);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (4, 7);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (4, 9);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (5, 1);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (5, 6);
INSERT INTO SUPERHERO_POWER (SUPERHERO_ID, SKILL_ID) VALUES (5, 11);
